steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/C-Shi/cicd-gke.git']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${CINAME}:${VERSION}', '.']

substitutions:
  PROJECT_ID: devops-cert-440119
  CINAME: gke-image
  VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY
