steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/C-Shi/cicd-gke.git']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

substitutions:
  _PROJECT_ID: devops-cert-440119
  _CINAME: gke-image
  _VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY
